#IMPORTANT: DOCKERFILE_PATH is not needed because we cd into each subdirectory build. This also means Dockerfile
#  commands that reference local files (e.g. COPY) must use relative paths to the same directory where the Dockerfile
#  is stored.

variables:
  DEBIAN_DISTRO: debian
  NGINX_STABLE_VERSION: "1.24"
  NGINX_MAINLINE_VERSION: "1.25.1"
  NGINX_STABLE_BRANCH: stable
  NGINX_MAINLINE_BRANCH: mainline

.nginx: &nginx
  trigger:
    include: 'nginx.gitlab-ci.yml'
    strategy: depend

Debian Nginx Stable:
  <<: *nginx
  variables:
    DISTRO: ${DEBIAN_DISTRO}
    NGINX_VERSION: ${NGINX_STABLE_VERSION}
    NGINX_BRANCH: ${NGINX_STABLE_BRANCH}

Debian Nginx Mainline:
  <<: *nginx
  variables:
    DISTRO: ${DEBIAN_DISTRO}
    NGINX_VERSION: ${NGINX_MAINLINE_VERSION}
    NGINX_BRANCH: ${NGINX_MAINLINE_BRANCH}
